In [7]:
from pathlib import Path
import pandas as pd
import numpy as np

print("Thư mục notebook đang chạy:")
print(Path.cwd())

Thư mục notebook đang chạy:
C:\Volume D\Hệ gợi ý\Jupyter\Project\notebooks

In [8]:
from pathlib import Path

NOTEBOOK_DIR = Path.cwd()
PROJECT_DIR = NOTEBOOK_DIR.parent

RAW_DIR = PROJECT_DIR / "data" / "raw"
EVENTS_PATH = RAW_DIR / "events.csv"

print("Project:", PROJECT_DIR)
print("Raw data:", RAW_DIR)
print("Events path:", EVENTS_PATH)
print("File tồn tại:", EVENTS_PATH.exists())

Project: C:\Volume D\Hệ gợi ý\Jupyter\Project
Raw data: C:\Volume D\Hệ gợi ý\Jupyter\Project\data\raw
Events path: C:\Volume D\Hệ gợi ý\Jupyter\Project\data\raw\events.csv
File tồn tại: True

In [9]:
events = pd.read_csv(
    EVENTS_PATH,
    dtype={
        "timestamp": "int64",
        "visitorid": "int32",
        "event": "category",
        "itemid": "int32",
        "transactionid": "float64"
    }
)

print("Đã đọc events.csv thành công")
print("Số dòng, số cột:", events.shape)

Đã đọc events.csv thành công
Số dòng, số cột: (2756101, 5)

In [10]:
events.head()

       timestamp  visitorid event  itemid  transactionid
0  1433221332117     257597  view  355908            NaN
1  1433224214164     992329  view  248676            NaN
2  1433221999827     111016  view  318965            NaN
3  1433221955914     483717  view  253185            NaN
4  1433221337106     951259  view  367447            NaN

In [11]:
events.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 2756101 entries, 0 to 2756100
Data columns (total 5 columns):
 #   Column         Dtype
---  ------         -----
 0   timestamp      int64
 1   visitorid      int32
 2   event          category
 3   itemid         int32
 4   transactionid  float64
dtypes: category(1), float64(1), int32(2), int64(1)
memory usage: 65.7 MB

In [9]:
print(events.columns.tolist())

['timestamp', 'visitorid', 'event', 'itemid', 'transactionid']

In [10]:
events["event"].value_counts()

event
view           2664312
addtocart        69332
transaction      22457
Name: count, dtype: int64

In [11]:
events.isna().sum()

timestamp              0
visitorid              0
event                  0
itemid                 0
transactionid    2733644
dtype: int64

In [12]:
events.loc[
    events["event"] == "transaction"
].isna().sum()

timestamp        0
visitorid        0
event            0
itemid           0
transactionid    0
dtype: int64

In [13]:
events["datetime"] = pd.to_datetime(
    events["timestamp"],
    unit="ms",
    utc=True
)

events[
    [
        "timestamp",
        "datetime",
        "visitorid",
        "event",
        "itemid"
    ]
].head()

       timestamp                         datetime  visitorid event  itemid
0  1433221332117 2015-06-02 05:02:12.117000+00:00     257597  view  355908
1  1433224214164 2015-06-02 05:50:14.164000+00:00     992329  view  248676
2  1433221999827 2015-06-02 05:13:19.827000+00:00     111016  view  318965
3  1433221955914 2015-06-02 05:12:35.914000+00:00     483717  view  253185
4  1433221337106 2015-06-02 05:02:17.106000+00:00     951259  view  367447

In [14]:
print("Bắt đầu:", events["datetime"].min())
print("Kết thúc:", events["datetime"].max())
print(
    "Số ngày:",
    (
        events["datetime"].max()
        - events["datetime"].min()
    ).days
)

Bắt đầu: 2015-05-03 03:00:04.384000+00:00
Kết thúc: 2015-09-18 02:59:47.788000+00:00
Số ngày: 137

In [15]:
print(
    "Số user:",
    events["visitorid"].nunique()
)

print(
    "Số item:",
    events["itemid"].nunique()
)

print(
    "Số giao dịch:",
    events["transactionid"].nunique()
)

Số user: 1407580
Số item: 235061
Số giao dịch: 17672

In [16]:
duplicate_count = events.duplicated().sum()

print(
    "Số dòng trùng hoàn toàn:",
    duplicate_count
)

Số dòng trùng hoàn toàn: 460

In [17]:
events[
    events.duplicated(keep=False)
].sort_values(
    [
        "visitorid",
        "timestamp",
        "itemid"
    ]
).head(20)

,timestamp,visitorid,event,itemid,transactionid,datetime
1041548,1440547735041,745,addtocart,246164,NaN,2015-08-26 00:08:55.041000+00:00
1051024,1440547735041,745,addtocart,246164,NaN,2015-08-26 00:08:55.041000+00:00
301904,1434501277715,3926,addtocart,323347,NaN,2015-06-17 00:34:37.715000+00:00
319376,1434501277715,3926,addtocart,323347,NaN,2015-06-17 00:34:37.715000+00:00
113491,1433611737367,10162,addtocart,146661,NaN,2015-06-06 17:28:57.367000+00:00
124035,1433611737367,10162,addtocart,146661,NaN,2015-06-06 17:28:57.367000+00:00
1965082,1432707397977,12046,addtocart,205663,NaN,2015-05-27 06:16:37.977000+00:00
1983425,1432707397977,12046,addtocart,205663,NaN,2015-05-27 06:16:37.977000+00:00
1166547,1441151647762,12560,addtocart,272976,NaN,2015-09-01 23:54:07.762000+00:00
1167841,1441151647762,12560,addtocart,272976,NaN,2015-09-01 23:54:07.762000+00:00
884721,1439754413562,26315,addtocart,157680,NaN,2015-08-16 19:46:53.562000+00:00
886677,1439754413562,26315,addtocart,157680,NaN,2015-08-16 19:46:53.562000+00:00
1023724,1440469490697,26429,addtocart,306482,NaN,2015-08-25 02:24:50.697000+00:00
1027606,1440469490697,26429,addtocart,306482,NaN,2015-08-25 02:24:50.697000+00:00
827181,1439520502395,27288,addtocart,239736,NaN,2015-08-14 02:48:22.395000+00:00
833110,1439520502395,27288,addtocart,239736,NaN,2015-08-14 02:48:22.395000+00:00
2678381,1438141817812,29482,addtocart,373384,NaN,2015-07-29 03:50:17.812000+00:00
2681100,1438141817812,29482,addtocart,373384,NaN,2015-07-29 03:50:17.812000+00:00
933441,1440046458149,32358,addtocart,252344,NaN,2015-08-20 04:54:18.149000+00:00
951006,1440046458149,32358,addtocart,252344,NaN,2015-08-20 04:54:18.149000+00:00

In [18]:
print(events.shape)
print(events["event"].value_counts())
print(events.duplicated().sum())

(2756101, 6)
event
view           2664312
addtocart        69332
transaction      22457
Name: count, dtype: int64
460